spring.application.name=logitrack



spring.datasource.url=jdbc:postgresql://aws-1-us-west-2.pooler.supabase.com:5432/postgres
spring.datasource.username=postgres.jgdkvfffzdxbzrdvsggo
spring.datasource.password=David_Dyonix15
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Schema por defecto

spring.jpa.properties.hibernate.default_schema=proyecto

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

jwt.secret=1q2w3e4r5t6y7u8i9oier982r28fidsoh2hf98ewhfewhf89whfsdihf982hf8hw98fh2h38fhsdhfsidhf98whf98sdhf89s9d8f
jwt.expiration-ms=86400000