# LogiTrack WMS - Configuración Spring Boot & Database
spring.application.name=logitrack
server.port=8080

# Configuración de Base de Datos PostgreSQL (Supabase)
spring.datasource.url=jdbc:postgresql://localhost:5432/logitrack_db?currentSchema=prueba
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuración Hibernate / JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.default_schema=prueba
spring.jpa.open-in-view=false

# Inicialización de Scripts SQL (desactivado por defecto para permitir a Hibernate DDL administrar el schema)
spring.sql.init.mode=never

# Configuración JWT
jwt.secret=1q2w3e4r5t6y7u8i9oier982r28fidsoh2hf98ewhfewhf89whfsdihf982hf8hw98fh2h38fhsdhfsidhf98whf98sdhf89s9d8f
jwt.expiration-ms=86400000

# OpenAPI / Swagger
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

